services:
  singboxsub:
    image: guaaaan244/singboxsub:v1.0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
