services:
  singbox-sub:
    image: ghcr.io/gu7432/singbox-sub:[tag]
    container_name: singbox-sub
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      ADMIN_PASSWORD: "0.00.0"

    volumes:
      - ./data:/app/data